# Generated by Django 6.0.3 on 2026-03-13 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(choices=[('qr', 'QR Scan'), ('manual', 'Manual Entry')], default='qr', max_length=10)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certificates.certificate')),
            ],
            options={
                'db_table': 'verification_logs',
                'ordering': ['-verified_at'],
            },
        ),
    ]
