# Generated by Django 6.0.3 on 2026-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='TAARUNYAM Platform', max_length=255)),
                ('brand_name', models.CharField(default='TAARUNYAM', max_length=255)),
                ('event_year', models.CharField(default='2026', max_length=4)),
                ('logo_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True, default='© TAARUNYAM 2026. All rights reserved.')),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('contact_email', models.EmailField(default='noreply@taarunyam.com', max_length=254)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=512)),
                ('cert_settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
