# Generated by Django 5.0.6 on 2026-03-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='categories_text',
            field=models.CharField(default='Coding • Robotics • Design', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='countdown_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='event_date_text',
            field=models.CharField(default='March 2026', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True, default='Experience the synergy of innovation and competition.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_title',
            field=models.CharField(default='TAARUNYAM 2026', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subtitle',
            field=models.CharField(default='The Ultimate Tech Championship', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='venue_text',
            field=models.CharField(default='University Campus', max_length=255),
        ),
    ]
