# Generated by Django 6.0.3 on 2026-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Knowledge', 'Knowledge'), ('Innovation', 'Innovation'), ('Web Development', 'Web Development'), ('Problem Solving', 'Problem Solving'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Robotics', 'Robotics'), ('Design', 'Design'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, default='code', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='prizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
